# Generated by Django 3.2 on 2021-05-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Medicines'), (2, 'Medical component'), (3, 'Supplement'), (4, 'Herb'), (5, 'Drag category N'), (6, 'Psychotropic category P I, II, III, IV'), (7, 'category B')])),
            ],
        ),
        migrations.CreateModel(
            name='Medicines_Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Ból'), (2, 'Przeciwzapalny'), (3, 'Przeciwgorączkowy'), (4, 'Nadciśnienie'), (5, 'Cholersterol'), (6, 'Depresja'), (7, 'Padaczka'), (8, 'Alzheimer'), (9, 'Reumatyzm'), (10, 'Uspakajające'), (11, 'Serce'), (12, 'Oko'), (13, 'Antybiotyk')])),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('gender', models.IntegerField(choices=[(1, 'Men'), (2, 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126, unique=True)),
                ('international_name', models.CharField(max_length=256)),
                ('dosage', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('category', models.ManyToManyField(to='medicines.Categorys')),
                ('medicines_action', models.ManyToManyField(to='medicines.Medicines_Actions')),
            ],
        ),
        migrations.CreateModel(
            name='FirstAidKits',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medicines.patients')),
                ('medicines', models.ManyToManyField(to='medicines.Medicines')),
            ],
        ),
    ]
