# Generated by Django 3.2 on 2021-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='category',
            field=models.ManyToManyField(null=True, to='medicines.Categorys'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='medicines_action',
            field=models.ManyToManyField(null=True, to='medicines.Medicines_Actions'),
        ),
    ]
