# Generated by Django 3.2 on 2021-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_auto_20210515_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='category',
            field=models.ManyToManyField(to='medicines.Categorys'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='medicines_action',
            field=models.ManyToManyField(to='medicines.Medicines_Actions'),
        ),
    ]
